  - alias: Master Bedroom Light Switch On
    trigger:
      platform: state
      entity_id: light.level
      to: on
    action:
      service: light.turn_on
      entity_id: light.level_2
      data:
        brightness: 100
  - alias: Master Bedroom Light Switch Off
    trigger:
      platform: state
      entity_id: light.level
      to: off
    action:
      service: light.turn_off
      entity_id: light.level_2
      data:
        brightness: 0
