- id: MBR_ON
  alias: Turn On Master Bedroom Lights
  trigger:
  - entity_id: light.level
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: light.level_2
    entity_id: light.level_2
    service: homeassistant.turn_off
- id: MBR_OFF
  alias: Turn Off Master Bedroom Lights
  trigger:
  - entity_id: light.level
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      entity_id: light.level_2
    entity_id: light.level_2
    service: homeassistant.turn_on
