homeassistant:
  name: Fiore Household
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

frontend:

# Enables configuration UI
config:

###############################################
#
# Load the iOS components
#
###############################################

#ios:

###############################################
#
# Load the http components
#
###############################################

http:
  api_password: !secret http_password
  base_url: https://dfiore.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

updater:

discovery:
  ignore:
    - plex_mediaserver
    - sonos
    - roku

history:

logbook:

logger:
  default: info

###############################################
#
# Integrations
#
###############################################

wink:
cloud:
alexa:
  filter:
    include_domains:
      - light
      - switch
    exclude_domains:
      - automation
      - group
      - script
      - sensor
      - media_player
tts:
  - platform: google
zwave:
  usb_path: /dev/ttyACM0

###############################################
#
# Includes
#
###############################################

# Static Includes
shell_command: !include shell_scripts.yaml
alarm_control_panel: !include alarm_com.yaml
automation: !include automations.yaml
sabnzbd: !include sabnzbd.yaml
dyson: !include dyson.yaml

# Merge Includes List
script: !include_dir_merge_list scripts
switch: !include_dir_merge_list switches

# Merge Includes Named
group: !include_dir_merge_named groups
intent_script: !include_dir_merge_named intentscripts
media_player: !include_dir_merge_named media_players
sensor: !include_dir_merge_list sensors
scene: !include_dir_merge_named scenes
