- alias: Turn On Master Bedroom Lights
  trigger:
    platform: state
    entity_id: light.master_bedroom_switch
    from: 'off'
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.master_bedroom_sconce
      brightness: 255
  condition:
   - platform: state
     entity_id: light.master_bedroom_switch
     state: 'off'
- alias: Turn Off Master Bedroom Lights
  trigger:
    platform: state
    entity_id: light.master_bedroom_switch
    from: 'om'
    to: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.master_bedroom_sconce
      brightness: 0
  condition:
   - platform: state
     entity_id: light.master_bedroom_switch
     state: 'on'
