- alias: Turn On Master Bedroom Lights
  trigger:
    platform: state
    entity_id: light.master_bedroom_switch
    from: 'on'
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: light.level_2

- alias: Turn Off Master Bedroom Lights
  trigger:
    platform: state
    entity_id: light.master_bedroom_switch
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.level_2
